# Generated by Django 3.0.2 on 2020-05-24 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=40)),
                ('release_day', models.DateField()),
                ('performer', models.ForeignKey(default='No performer', on_delete=django.db.models.deletion.SET_DEFAULT, to='webApi.Performer')),
            ],
        ),
    ]
