# Generated by Django 3.0.2 on 2020-05-24 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0005_auto_20200525_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='performer',
            field=models.ForeignKey(default='No performer', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='webApi.Performer', to_field='performer_name'),
        ),
    ]
