# Generated by Django 3.0.2 on 2020-05-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0009_auto_20200525_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='music_service',
            field=models.ManyToManyField(null=True, related_name='ms_tracks', to='webApi.MusicService'),
        ),
    ]
