# Generated by Django 3.0.2 on 2020-05-25 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0010_auto_20200525_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='music_service',
        ),
    ]
