# Generated by Django 3.0.2 on 2020-05-25 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0011_remove_track_music_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='music_service',
            field=models.ManyToManyField(null=True, related_name='ms_tracks', to='webApi.MusicService'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(default='No genre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g_tracks', to='webApi.Genre', to_field='genre_name'),
        ),
    ]
