# Generated by Django 3.0.2 on 2020-05-25 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0012_auto_20200525_0315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
