# Generated by Django 3.0.2 on 2020-05-25 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0013_delete_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=30)),
                ('genre', models.ForeignKey(default='No genre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g_tracks', to='webApi.Genre', to_field='genre_name')),
            ],
        ),
    ]
