# Generated by Django 3.0.2 on 2020-05-25 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0017_auto_20200525_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_tracks', to='webApi.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='music_service',
            field=models.ManyToManyField(blank=True, related_name='ms_tracks', to='webApi.MusicService'),
        ),
    ]
