# Generated by Django 3.0.3 on 2020-05-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0018_auto_20200525_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
