# Generated by Django 3.0.3 on 2020-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0020_remove_performer_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
