# Generated by Django 3.0.2 on 2020-05-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='music_service',
            new_name='music_service_t',
        ),
    ]
