# Generated by Django 3.0.3 on 2020-05-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0019_auto_20200528_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='birthday',
        ),
    ]
